[package]
name = "lenia"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.12", features = ["async-std", "canvas"] }
itertools = "0.14.0"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.9.0"
rand_distr = "0.5.1"
rayon = "1.10.0"
